extends: airbnb-base
plugins:
  - import
rules:
  no-underscore-dangle:
  - error
  - allowAfterThis: true
  space-before-function-paren:
  - error
  - named: always
  comma-dangle:
  - error
  - never
  no-console:
  - off
  max-len: 
  - error
  - 120
  no-unused-expressions:
  - error
  - allowShortCircuit: true
  strict: off
